export const profileStrings = {
  traveler: 'Traveler',
  profileSubtitle: 'Your Syunik travel profile',
  changePhoto: 'Change profile photo',
  photoLabel: 'Profile photo',
  photoUpdated: 'Profile photo updated.',
  photoSelectError: 'Could not select a profile photo.',
  photoSaveError: 'Could not save the profile photo.',
  description: 'Keep your contact details and the places you love in one place.',
  stats: {visited: 'Visited', favorites: 'Favorites', badges: 'Badges'},
  personalInfo: {
    title: 'Personal information',
    name: 'Name',
    email: 'Email',
    phone: 'Phone number',
    namePlaceholder: 'Enter your name',
    emailPlaceholder: 'you@example.com',
    phonePlaceholder: 'Phone number',
    edit: 'Edit profile',
    save: 'Save changes',
    cancel: 'Cancel',
    saving: 'Saving...',
    requiredName: 'Enter your name.',
    requiredEmail: 'Enter your email address.',
    invalidEmail: 'Enter a valid email address.',
    requiredPhone: 'Enter your phone number.',
    invalidPhone: 'Enter a valid phone number.',
    saveError: 'Could not save your profile. Please try again.',
    saveSuccess: 'Profile details saved.',
    selectCountry: 'Select country code',
  },
  favorites: {
    title: 'Favorite places',
    description: 'Save places you want to visit.',
    search: 'Search places',
    emptyTitle: 'No favorites yet',
    emptyDescription: 'Save a place to keep it close.',
    browse: 'Browse places',
    noMatches: 'No matching places.',
    added: 'Favorite place saved.',
    removed: 'Favorite place removed.',
    addError: 'Could not save favorite place.',
    removeError: 'Could not update favorite places.',
    selectHint: 'Choose a place from the suggestions.',
    duplicate: 'That place is already a favorite.',
    remove: 'Remove favorite',
    exploreAdded: 'Added to favorites.',
    exploreRemoved: 'Removed from favorites.',
    exploreSaveError: 'Could not update favorites. Please try again.',
    addFromExplore: 'Add to favorites',
    removeFromExplore: 'Remove from favorites',
  },
  visits: {
    title: 'Visiting history',
    description: 'Keep a record of the places you have visited.',
    search: 'Search places',
    noMatches: 'No matching places.',
    emptyTitle: 'Your next visit starts here',
    emptyDescription: 'Add a place and the date you visited.',
    addFirst: 'Add a visit',
    chooseDate: 'Choose visit date',
    delete: 'Delete visit',
    confirmDelete: 'Remove this visit from your history?',
    deleted: 'Visit removed.',
    added: 'Visit saved to your history.',
    addError: 'Could not save visiting history.',
    selectHint: 'Choose a place from the suggestions first.',
    removeError: 'Could not update visiting history.',
  },
  settings: {
    title: 'Settings',
    language: 'Language',
    notifications: 'Notifications',
    logout: 'Log out',
    deleteAccount: 'Delete account',
    deleteTitle: 'Delete account?',
    deleteMessage: 'This action cannot be undone.',
    confirmDelete: 'Delete',
    cancel: 'Cancel',
    logoutUnavailable: 'There is no signed-in account to log out.',
    deleteUnavailable: 'Account deletion is unavailable until an account service is connected.',
    saveError: 'Could not save settings. Please try again.',
  },
  common: {
    retry: 'Retry',
    loadError: 'Could not load profile details.',
    loading: 'Loading profile...',
    dismiss: 'Dismiss',
  },
} as const;